name: Ruby

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Remove data schema so we bootstrap from zero with data migrations
        run: rm db/data_schema.rb
      - name: Set up database with prepare command so we catch any migration explosions
        run: bundle exec rails db:prepare:with_data
        env:
          RAILS_ENV: test
      - name: Check typescript
        run: yarn typecheck
      - name: Compile assets
        run: bundle exec rails assets:precompile
      - name: Run tests
        uses: paambaati/codeclimate-action@v9.0.0
        with:
          coverageCommand: bundle exec rake
        env:
          CC_TEST_REPORTER_ID: f570c8191542a0db2056d5994b06e9d0be35b25bc6897b5e913c1b783b920a0a
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Lint Ruby code
        run: bundle exec rake rubocop
      - name: Lint ERB templates
        run: bundle exec erb_lint --lint-all
      - name: Lint Typescript code
        run: yarn run lint:ts
  i18n:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Check translations
        run: bundle exec i18n-tasks health -l en
